name: Simulator

on:
  # Triggers the workflow on push or pull request for the given branch
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

  # Trigger manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        simulators:
          - riscv/griscv
          - sparc/gr740
          - arm/xilinx_zynq_a9_qemu
    runs-on: ubuntu-latest
    steps:
      - name: split arch and BSP
        shell: bash
        run: |
          arch=`echo "${{ matrix.simulators }}" | sed -e "s|/.*||g"`
          bsp=`echo "${{ matrix.simulators }}" | sed -e "s|.*/||g"`
          echo "arch=${arch}" >> $GITHUB_ENV
          echo "bsp=${bsp}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          path: rtems
      - uses: actions/checkout@v3
        with:
          path: rtems-actions
          ref: ci
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
            python3 \
            python-is-python3 \
            jq
      - name: Download toolchain artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: embedded-brains/rtems-source-builder
          branch: ci
          workflow: toolchain.yml
          workflow_conclusion: completed
          name: tools-${{ env.arch }}
      - name: Download qemu artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: embedded-brains/rtems-source-builder
          branch: ci
          workflow: toolchain.yml
          workflow_conclusion: completed
          name: devel-qemu
      - name: Unpack toolchain
        run: |
          mkdir -p "$GITHUB_WORKSPACE/toolchain"
          for t in *.tar.bz2; do tar xf $t -v -C "$GITHUB_WORKSPACE/toolchain"; done
          ls -la "$GITHUB_WORKSPACE/toolchain"
      - name: Start simulator run
        id: simulator
        uses: ./rtems-actions/.github/actions/run-simulator
        with:
          target: ${{ matrix.simulators }}
          sources-rtems: "$GITHUB_WORKSPACE/rtems"
          prefix: "$GITHUB_WORKSPACE/toolchain/opt/rtems/6"
